id: I56EDA695
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:23:04+00:00'
last_modified: '2022-06-08T11:27:36.087120+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137838
  title: གཡུ་ཁོག་རྒྱ་སྤྲུལ་རིག་འཛིན་ལུང་རིག་གླིང་པའི་གསུང་འབུམ་གཅེས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    824A:
      image_group_id: I2PD18305
      title: ''
      total_pages: 255
      order: 1
      base_file: 824A.txt
    '4484':
      image_group_id: I2PD18306
      title: ''
      total_pages: 361
      order: 2
      base_file: 4484.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
