id: P009498
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137838
  title: གཡུ་ཁོག་རྒྱ་སྤྲུལ་རིག་འཛིན་ལུང་རིག་གླིང་པའི་གསུང་འབུམ་གཅེས་བསྡུས།
  author: ''
  volumes:
    e115b65cf3494e6595a1a4e54016a86d:
      image_group_id: I2PD18305
      title: ''
      volume_number: 1
      total_pages: 255
      base_file: v001.txt
    6f438fc1e88b4365837b001a2ae72711:
      image_group_id: I2PD18306
      title: ''
      volume_number: 2
      total_pages: 361
      base_file: v002.txt
